### ISSUE TITLE
Validate json message on server side

### ISSUE THREAD

**Issue by kremius** [kremius/karya-valya#128]
Type: ordinary. json: {"nokey":"hey"}

**Comment by kremius** [comment]
To Release cause it is really important

**Comment by kremius** [comment]
Or in server (probably server is better)

**Comment by kremius** [comment]
It is needed to make some server key "-nostrict".
With this key enables server will not check messages.
It is needed for easy development

**Comment by kremius** [comment]
Also it is needed to check messages sizes

**Comment by mechmind** [comment]
Reopen if something breaks
