### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by kremius** [kremius/karya-valya#159]
A lot of people, master client has crashed

**Comment by kremius** [comment]
It is needed to check id of game object in the message handling in the manager
Currently for some reason crash in Ghost
Maybe connected?

**Comment by kremius** [comment]
The bug with Ghost is reproduced in 0.2.0 -> the reason of the bug is here

**Comment by kremius** [comment]
"It is needed to check id of game object in the message handling in the manager" -> wrong
The bug was about MoveEffect

**Comment by kremius** [comment]
Still not fixed -> MoveEffect bug appeared after 0.2.0 release.

**Comment by kremius** [comment]
`C:\Users\Kremius\Documents\Qt\KVEngineQt\knv-server-go>knv-server-go.exe -db-roo
t=db-local
2016/02/28 02:52:14 client: registering client
2016/02/28 02:52:14 registry: registered new id 1 for player 'Admin'
2016/02/28 02:52:14 registry: creating new unit for client 1, login 'Admin'
2016/02/28 02:52:14 client[1]: registered, is it master? true
2016/02/28 02:52:14 client[1]: starting main loop
2016/02/28 02:52:38 client: registering client
2016/02/28 02:52:38 registry: reusing existing id 1 for player 'Admin'
2016/02/28 02:52:38 registry: no players left, cleaning up
2016/02/28 02:52:38 registry: registered new id 1 for player 'Admin'
2016/02/28 02:52:38 registry: creating new unit for client 1, login 'Admin'
2016/02/28 02:52:38 client[1]: inbox closed, closing connection
2016/02/28 02:52:38 client[1]: registered, is it master? true
2016/02/28 02:52:38 client[1]: starting main loop
2016/02/28 02:52:57 client: registering client
2016/02/28 02:52:57 registry: registered new id 2 for player 'Guest2673'
2016/02/28 02:52:57 registry: creating new unit for client 2, login 'Guest2673'
2016/02/28 02:52:57 client[2]: registered, is it master? false
2016/02/28 02:52:57 client[2]: starting main loop
2016/02/28 02:52:57 registry: requesting master 1 to send map
2016/02/28 02:52:58 hash-check: master 1 did not sent his hash
2016/02/28 02:52:58 hash-check: master 1 did not sent his hash
2016/02/28 02:52:58 hash-check: master 1 did not sent his hash
2016/02/28 02:52:58 hash-check: master 1 did not sent his hash
2016/02/28 02:52:58 hash-check: master 1 did not sent his hash
2016/02/28 02:52:58 hash-check: master 1 did not sent his hash
2016/02/28 02:52:58 hash-check: master 1 did not sent his hash
2016/02/28 02:52:58 hash-check: master 1 did not sent his hash
2016/02/28 02:52:58 hash-check: master 1 did not sent his hash
2016/02/28 02:52:59 hash-check: master 1 did not sent his hash
2016/02/28 02:52:59 hash-check: master 1 did not sent his hash
2016/02/28 02:52:59 hash-check: master 1 did not sent his hash
2016/02/28 02:52:59 hash-check: master 1 did not sent his hash
2016/02/28 02:52:59 hash-check: master 1 did not sent his hash
2016/02/28 02:52:59 hash-check: master 1 did not sent his hash
2016/02/28 02:52:59 hash-check: master 1 did not sent his hash
2016/02/28 02:52:59 hash-check: master 1 did not sent his hash
2016/02/28 02:52:59 hash-check: master 1 did not sent his hash
2016/02/28 02:52:59 hash-check: master 1 did not sent his hash
2016/02/28 02:53:00 hash-check: master 1 did not sent his hash
2016/02/28 02:53:00 hash-check: master 1 did not sent his hash
2016/02/28 02:53:00 hash-check: master 1 did not sent his hash
2016/02/28 02:53:00 hash-check: master 1 did not sent his hash
2016/02/28 02:53:00 hash-check: master 1 did not sent his hash
2016/02/28 02:53:00 hash-check: master 1 did not sent his hash
2016/02/28 02:53:00 hash-check: master 1 did not sent his hash
2016/02/28 02:53:00 hash-check: master 1 did not sent his hash
2016/02/28 02:53:00 hash-check: master 1 did not sent his hash
2016/02/28 02:53:00 hash-check: master 1 did not sent his hash
2016/02/28 02:53:01 hash-check: master 1 did not sent his hash
2016/02/28 02:53:01 hash-check: master 1 did not sent his hash
2016/02/28 02:53:01 hash-check: master 1 did not sent his hash
2016/02/28 02:53:01 hash-check: master 1 did not sent his hash
2016/02/28 02:53:01 hash-check: master 1 did not sent his hash
2016/02/28 02:53:01 hash-check: master 1 did not sent his hash
2016/02/28 02:53:01 hash-check: master 1 did not sent his hash
2016/02/28 02:53:01 hash-check: master 1 did not sent his hash
2016/02/28 02:53:01 hash-check: master 1 did not sent his hash
2016/02/28 02:53:01 hash-check: master 1 did not sent his hash
2016/02/28 02:53:02 hash-check: master 1 did not sent his hash
2016/02/28 02:53:02 hash-check: master 1 did not sent his hash
2016/02/28 02:53:02 hash-check: master 1 did not sent his hash
2016/02/28 02:53:02 client[1]: reciever failed to read message: WSARecv tcp 127.
0.0.1:1111: An existing connection was forcibly closed by the remote host.
2016/02/28 02:53:02 hash-check: master 2 did not sent his hash
2016/02/28 02:53:02 hash-check: master 2 did not sent his hash
2016/02/28 02:53:02 hash-check: master 2 did not sent his hash
2016/02/28 02:53:02 hash-check: master 2 did not sent his hash
2016/02/28 02:53:02 hash-check: master 2 did not sent his hash
2016/02/28 02:53:04 client[2]: reciever failed to read message: WSARecv tcp 127.
0.0.1:1111: An existing connection was forcibly closed by the remote host.
2016/02/28 02:53:04 registry: no players left, cleaning up`

**Comment by kremius** [comment]
Launch client with login == 'Admin', launch second client with login == 'Admin' (the first admin client will be disconnected). Then launch next client with login == 'Guest' -> tick_mismatch will popup in the client. 

New client  10304
Map upload to  "http://localhost:8011/?id=4574640382776250421" , tick  427
Current game tick:  191
It took  0 ms to send the map
Map has been sended to  "http://localhost:8011/?id=4574640382776250421" , length:  4
Tick mismatch!  428   192

The server does not reset tick counts when admin relogin occurs. Probably it should be forbidden to relogin (the server should send something like 'ALREADY_CONNECTED' back on relogin request from the client).

**Comment by mechmind** [comment]
Fixed reset on new game, please check it out.

**Comment by kremius** [comment]
Seems like fixed
