### ISSUE TITLE
Server randomly drops every connection

### ISSUE THREAD

**Issue by kremius** [kremius/karya-valya#162]
And round is restarting

**Comment by kremius** [comment]
2016/03/05 04:02:05 client: registering client
2016/03/05 04:02:05 registry: registered new id 1 for player 'backdoor-admin'
2016/03/05 04:02:05 registry: creating new unit for client 1, login 'backdoor-ad
min'
2016/03/05 04:02:05 client[1]: registered, is it master? true
2016/03/05 04:02:05 client[1]: starting main loop
2016/03/05 04:02:30 client: registering client
2016/03/05 04:02:30 registry: registered new id 2 for player 'Guest580'
2016/03/05 04:02:30 registry: creating new unit for client 2, login 'Guest580'
2016/03/05 04:02:30 registry: requesting master 1 to send map
2016/03/05 04:02:30 client[2]: registered, is it master? false
2016/03/05 04:02:30 client[2]: starting main loop
2016/03/05 04:02:30 client: registering client
2016/03/05 04:02:30 registry: registered new id 3 for player 'Guest5026'
2016/03/05 04:02:30 registry: creating new unit for client 3, login 'Guest5026'
2016/03/05 04:02:30 client[3]: registered, is it master? false
2016/03/05 04:02:30 client[3]: starting main loop
2016/03/05 04:02:30 client: registering client
2016/03/05 04:02:30 registry: registered new id 4 for player 'Guest1230'
2016/03/05 04:02:31 registry: creating new unit for client 4, login 'Guest1230'
2016/03/05 04:02:31 client[4]: registered, is it master? false
2016/03/05 04:02:31 client[4]: starting main loop
2016/03/05 04:02:31 registry: requesting master 1 to send map
2016/03/05 04:02:31 registry: requesting master 1 to send map
2016/03/05 04:02:31 client: registering client
2016/03/05 04:02:31 registry: registered new id 5 for player 'Guest2641'
2016/03/05 04:02:31 registry: creating new unit for client 5, login 'Guest2641'
2016/03/05 04:02:31 client[5]: registered, is it master? false
2016/03/05 04:02:31 client[5]: starting main loop
2016/03/05 04:02:31 registry: requesting master 1 to send map
2016/03/05 04:02:31 hash-check: master 1 did not sent his hash
2016/03/05 04:02:31 hash-check: master 1 did not sent his hash
2016/03/05 04:02:31 hash-check: master 1 did not sent his hash
2016/03/05 04:02:32 hash-check: master 1 did not sent his hash
2016/03/05 04:02:32 client[3]: sender failed to send message: WSASend tcp 127.0.
0.1:1111: An existing connection was forcibly closed by the remote host.
2016/03/05 04:02:32 hash-check: master 1 did not sent his hash
2016/03/05 04:02:32 hash-check: master 1 did not sent his hash
2016/03/05 04:02:32 hash-check: master 1 did not sent his hash
2016/03/05 04:02:32 client[4]: reciever failed to read message: WSARecv tcp 127.
0.0.1:1111: An existing connection was forcibly closed by the remote host.
2016/03/05 04:02:32 hash-check: master 1 did not sent his hash
2016/03/05 04:02:32 hash-check: master 1 did not sent his hash
2016/03/05 04:02:32 hash-check: master 1 did not sent his hash
2016/03/05 04:02:32 hash-check: master 1 did not sent his hash
2016/03/05 04:02:32 hash-check: master 1 did not sent his hash
2016/03/05 04:02:33 hash-check: master 1 did not sent his hash
2016/03/05 04:02:33 hash-check: master 1 did not sent his hash
2016/03/05 04:02:33 hash-check: master 1 did not sent his hash
2016/03/05 04:02:33 hash-check: master 1 did not sent his hash
2016/03/05 04:02:33 client: registering client
2016/03/05 04:02:33 registry: registered new id 6 for player 'Guest2646'
2016/03/05 04:02:33 registry: creating new unit for client 6, login 'Guest2646'
2016/03/05 04:02:33 client[6]: registered, is it master? false
2016/03/05 04:02:33 client[6]: starting main loop
2016/03/05 04:02:33 hash-check: master 1 did not sent his hash
2016/03/05 04:02:33 hash-check: master 1 did not sent his hash
2016/03/05 04:02:33 registry: requesting master 1 to send map
2016/03/05 04:02:33 hash-check: master 1 did not sent his hash
2016/03/05 04:02:34 client: registering client
2016/03/05 04:02:34 registry: registered new id 7 for player 'Guest2625'
2016/03/05 04:02:34 registry: creating new unit for client 7, login 'Guest2625'
2016/03/05 04:02:34 client[7]: registered, is it master? false
2016/03/05 04:02:34 client[7]: starting main loop
2016/03/05 04:02:34 registry: requesting master 1 to send map
2016/03/05 04:02:34 client: registering client
2016/03/05 04:02:34 registry: registered new id 8 for player 'Guest2387'
2016/03/05 04:02:34 registry: creating new unit for client 8, login 'Guest2387'
2016/03/05 04:02:34 registry: requesting master 1 to send map
2016/03/05 04:02:34 client[8]: registered, is it master? false
2016/03/05 04:02:34 client[8]: starting main loop
2016/03/05 04:02:34 hash-check: master 1 did not sent his hash
2016/03/05 04:02:35 hash-check: master 1 did not sent his hash
2016/03/05 04:02:35 hash-check: master 1 did not sent his hash
2016/03/05 04:02:35 hash-check: master 1 did not sent his hash
2016/03/05 04:02:35 hash-check: master 1 did not sent his hash
2016/03/05 04:02:35 hash-check: master 1 did not sent his hash
2016/03/05 04:02:35 hash-check: master 1 did not sent his hash
2016/03/05 04:02:35 hash-check: master 1 did not sent his hash
2016/03/05 04:02:35 hash-check: master 1 did not sent his hash
2016/03/05 04:02:35 hash-check: master 1 did not sent his hash
2016/03/05 04:02:36 hash-check: master 1 did not sent his hash
2016/03/05 04:02:37 client[2]: sender failed to send message: WSASend tcp 127.0.
0.1:1111: An existing connection was forcibly closed by the remote host.
2016/03/05 04:02:38 hash-check: master 1 did not sent his hash
2016/03/05 04:02:38 hash-check: master 1 did not sent his hash
2016/03/05 04:02:38 hash-check: master 1 did not sent his hash
2016/03/05 04:02:38 hash-check: master 1 did not sent his hash
2016/03/05 04:02:39 hash-check: master 1 did not sent his hash
2016/03/05 04:02:45 hash-check: master 1 did not sent his hash
2016/03/05 04:02:45 hash-check: master 1 did not sent his hash
2016/03/05 04:02:46 client: registering client
2016/03/05 04:02:46 registry: registered new id 9 for player 'Guest7567'
2016/03/05 04:02:46 registry: creating new unit for client 9, login 'Guest7567'
2016/03/05 04:02:46 client[9]: registered, is it master? false
2016/03/05 04:02:46 client[9]: starting main loop
2016/03/05 04:02:46 registry: requesting master 1 to send map
2016/03/05 04:02:46 hash-check: master 1 did not sent his hash
2016/03/05 04:02:46 hash-check: master 1 did not sent his hash
2016/03/05 04:02:47 hash-check: master 1 did not sent his hash
2016/03/05 04:02:47 hash-check: master 1 did not sent his hash
2016/03/05 04:02:47 hash-check: master 1 did not sent his hash
2016/03/05 04:02:47 hash-check: master 1 did not sent his hash
2016/03/05 04:02:47 hash-check: master 1 did not sent his hash
2016/03/05 04:02:47 hash-check: master 1 did not sent his hash
2016/03/05 04:02:47 hash-check: master 1 did not sent his hash
2016/03/05 04:02:47 hash-check: master 1 did not sent his hash
2016/03/05 04:02:48 hash-check: master 1 did not sent his hash
2016/03/05 04:02:48 hash-check: master 1 did not sent his hash
2016/03/05 04:02:49 hash-check: master 1 did not sent his hash
2016/03/05 04:02:49 client: registering client
2016/03/05 04:02:49 registry: registered new id 10 for player 'Guest3010'
2016/03/05 04:02:49 registry: creating new unit for client 10, login 'Guest3010'

2016/03/05 04:02:49 client[10]: registered, is it master? false
2016/03/05 04:02:49 client[10]: starting main loop
2016/03/05 04:02:49 registry: requesting master 1 to send map
2016/03/05 04:02:50 client: registering client
2016/03/05 04:02:50 registry: registered new id 11 for player 'Guest2678'
2016/03/05 04:02:50 registry: creating new unit for client 11, login 'Guest2678'

2016/03/05 04:02:50 client[11]: registered, is it master? false
2016/03/05 04:02:50 client[11]: starting main loop
2016/03/05 04:02:50 registry: requesting master 1 to send map
2016/03/05 04:02:51 hash-check: master 1 did not sent his hash
2016/03/05 04:02:51 hash-check: master 1 did not sent his hash
2016/03/05 04:02:51 hash-check: master 1 did not sent his hash
2016/03/05 04:02:52 hash-check: master 1 did not sent his hash
2016/03/05 04:02:53 hash-check: master 1 did not sent his hash
2016/03/05 04:02:54 hash-check: master 1 did not sent his hash
2016/03/05 04:02:54 hash-check: master 1 did not sent his hash
2016/03/05 04:02:55 hash-check: master 1 did not sent his hash
2016/03/05 04:02:55 hash-check: master 1 did not sent his hash
2016/03/05 04:02:56 hash-check: master 1 did not sent his hash
2016/03/05 04:02:56 hash-check: master 1 did not sent his hash
2016/03/05 04:02:57 hash-check: master 1 did not sent his hash
2016/03/05 04:02:57 hash-check: master 1 did not sent his hash
2016/03/05 04:02:57 hash-check: master 1 did not sent his hash
2016/03/05 04:02:58 hash-check: master 1 did not sent his hash
2016/03/05 04:02:58 hash-check: master 1 did not sent his hash
2016/03/05 04:02:58 hash-check: master 1 did not sent his hash
2016/03/05 04:02:58 hash-check: master 1 did not sent his hash
2016/03/05 04:02:58 hash-check: master 1 did not sent his hash
2016/03/05 04:02:58 hash-check: master 1 did not sent his hash
2016/03/05 04:02:58 hash-check: master 1 did not sent his hash
2016/03/05 04:02:58 hash-check: master 1 did not sent his hash
2016/03/05 04:02:59 hash-check: master 1 did not sent his hash
2016/03/05 04:02:59 hash-check: master 1 did not sent his hash
2016/03/05 04:02:59 hash-check: master 1 did not sent his hash
2016/03/05 04:02:59 hash-check: master 1 did not sent his hash
2016/03/05 04:02:59 hash-check: master 1 did not sent his hash
2016/03/05 04:02:59 hash-check: master 1 did not sent his hash
2016/03/05 04:02:59 hash-check: master 1 did not sent his hash
2016/03/05 04:02:59 hash-check: master 1 did not sent his hash
2016/03/05 04:02:59 hash-check: master 1 did not sent his hash
2016/03/05 04:02:59 hash-check: master 1 did not sent his hash
2016/03/05 04:03:00 hash-check: master 1 did not sent his hash
2016/03/05 04:03:00 hash-check: master 1 did not sent his hash
2016/03/05 04:03:00 hash-check: master 1 did not sent his hash
2016/03/05 04:03:00 hash-check: master 1 did not sent his hash
2016/03/05 04:03:00 hash-check: master 1 did not sent his hash
2016/03/05 04:03:00 hash-check: master 1 did not sent his hash
2016/03/05 04:03:00 hash-check: master 1 did not sent his hash
2016/03/05 04:03:01 hash-check: master 1 did not sent his hash
2016/03/05 04:03:01 hash-check: master 1 did not sent his hash
2016/03/05 04:03:01 hash-check: master 1 did not sent his hash
2016/03/05 04:03:01 hash-check: master 1 did not sent his hash
2016/03/05 04:03:01 hash-check: master 1 did not sent his hash
2016/03/05 04:03:02 hash-check: master 1 did not sent his hash
2016/03/05 04:03:02 hash-check: master 1 did not sent his hash
2016/03/05 04:03:02 hash-check: master 1 did not sent his hash
2016/03/05 04:03:03 hash-check: master 1 did not sent his hash
2016/03/05 04:03:03 hash-check: master 1 did not sent his hash
2016/03/05 04:03:03 hash-check: master 1 did not sent his hash
2016/03/05 04:03:03 hash-check: master 1 did not sent his hash
2016/03/05 04:03:03 registry: no players left, cleaning up
2016/03/05 04:03:03 client[9]: inbox closed, closing connection
2016/03/05 04:03:03 client[10]: inbox closed, closing connection
2016/03/05 04:03:03 client[8]: inbox closed, closing connection
2016/03/05 04:03:03 client[5]: inbox closed, closing connection
2016/03/05 04:03:03 client[6]: inbox closed, closing connection
2016/03/05 04:03:03 client[1]: inbox closed, closing connection
2016/03/05 04:03:03 client[11]: inbox closed, closing connection
2016/03/05 04:03:03 client[7]: inbox closed, closing connection
2016/03/05 04:03:09 client: registering client
2016/03/05 04:03:12 client: registering client
2016/03/05 04:03:12 client: registering client
2016/03/05 04:03:14 client: registering client
2016/03/05 04:03:14 client: registering client
2016/03/05 04:03:14 client: registering client
2016/03/05 04:03:15 client: registering client
2016/03/05 04:03:15 client: registering client

**Comment by kremius** [comment]
The bug was reproduced. Just a lot of clients try to login in the same moment

**Comment by kremius** [comment]
Additionaly, the server randomly closing connections
2016/03/05 04:10:53 registry: requesting master 1 to send map
2016/03/05 04:10:54 hash-check: master 1 did not sent his hash
2016/03/05 04:10:54 hash-check: master 1 did not sent his hash
2016/03/05 04:10:54 hash-check: master 1 did not sent his hash
2016/03/05 04:10:54 hash-check: master 1 did not sent his hash
2016/03/05 04:12:00 client[12]: inbox closed, closing connection
2016/03/05 04:12:51 client[11]: inbox closed, closing connection
2016/03/05 04:13:09 client[1]: inbox closed, closing connection
2016/03/05 04:14:07 client[3]: inbox closed, closing connection
2016/03/05 04:14:15 client[7]: inbox closed, closing connection

**Comment by kremius** [comment]
Additionaly, no messages about changing master when 1 inbox was closed

2016/03/05 04:13:09 client[1]: inbox closed, closing connection
2016/03/05 04:14:07 client[3]: inbox closed, closing connection
2016/03/05 04:14:15 client[7]: inbox closed, closing connection
2016/03/05 04:15:05 client[13]: inbox closed, closing connection
2016/03/05 04:16:32 client: registering client
2016/03/05 04:16:32 registry: reusing existing id 1 for player 'backdoor-admin'
2016/03/05 04:16:32 client[1]: registered, is it master? false
2016/03/05 04:16:32 client[1]: starting main loop
2016/03/05 04:16:32 registry: requesting master 10 to send map
2016/03/05 04:17:02 client[8]: inbox closed, closing connection
2016/03/05 04:17:05 client[1]: reciever failed to read message: EOF
2016/03/05 04:17:10 client[10]: reciever failed to read message: EOF
2016/03/05 04:17:10 registry: no players left, cleaning up

**Comment by mechmind** [comment]
I added some verbosity to registry log. Seems like client does not read messages while it sends or recieves a map.

**Comment by kremius** [comment]
2016/03/06 13:44:52 client[29]: registered, is it master? false
2016/03/06 13:44:52 client[29]: starting main loop
2016/03/06 13:44:52 registry: requesting master 1 to send map
2016/03/06 13:45:00 hash-check: master 1 did not sent his hash
2016/03/06 13:45:01 hash-check: master 1 did not sent his hash
2016/03/06 13:45:01 hash-check: master 1 did not sent his hash
2016/03/06 13:45:01 hash-check: master 1 did not sent his hash
2016/03/06 13:45:01 hash-check: master 1 did not sent his hash
2016/03/06 13:45:01 hash-check: master 1 did not sent his hash
2016/03/06 13:45:01 hash-check: master 1 did not sent his hash
2016/03/06 13:45:02 registry: removing client 1 with message: ErrmsgTooSlow
2016/03/06 13:45:02 registry: switching master 1 -> 26
2016/03/06 13:45:02 client[1]: inbox closed, closing connection
2016/03/06 13:45:05 client[26]: sender failed to send message: WSASend tcp 127.0
.0.1:1111: An existing connection was forcibly closed by the remote host.
2016/03/06 13:45:05 registry: removing client 26
2016/03/06 13:45:05 registry: switching master 26 -> 27
2016/03/06 13:45:07 client: registering client
2016/03/06 13:45:07 registry: registered new id 30 for player 'Guest1290'
2016/03/06 13:45:07 registry: creating new unit for client 30, login 'Guest1290'

2016/03/06 13:45:07 client[30]: registered, is it master? false
2016/03/06 13:45:07 client[30]: starting main loop
2016/03/06 13:45:07 registry: requesting master 27 to send map
2016/03/06 13:45:15 client[30]: reciever failed to read message: WSARecv tcp 127
.0.0.1:1111: An existing connection was forcibly closed by the remote host.
2016/03/06 13:45:15 registry: removing client 30
2016/03/06 13:45:17 client: registering client
2016/03/06 13:45:17 registry: registered new id 31 for player 'Guest3075'
2016/03/06 13:45:17 registry: creating new unit for client 31, login 'Guest3075'

2016/03/06 13:45:17 client[31]: registered, is it master? false
2016/03/06 13:45:17 client[31]: starting main loop
2016/03/06 13:45:17 registry: requesting master 27 to send map
2016/03/06 13:45:37 client: registering client
2016/03/06 13:45:37 registry: registered new id 32 for player 'Guest3680'
2016/03/06 13:45:37 registry: creating new unit for client 32, login 'Guest3680'

2016/03/06 13:45:37 client[32]: registered, is it master? false
2016/03/06 13:45:37 client[32]: starting main loop
2016/03/06 13:45:37 registry: requesting master 27 to send map
2016/03/06 13:45:40 client[31]: reciever failed to read message: WSARecv tcp 127
.0.0.1:1111: An existing connection was forcibly closed by the remote host.
2016/03/06 13:45:40 registry: removing client 31
2016/03/06 13:45:40 client[32]: sender failed to send message: WSASend tcp 127.0
.0.1:1111: An existing connection was forcibly closed by the remote host.
2016/03/06 13:45:40 registry: removing client 32
2016/03/06 13:45:42 client: registering client
2016/03/06 13:45:42 registry: registered new id 33 for player 'Guest5193'
2016/03/06 13:45:42 registry: creating new unit for client 33, login 'Guest5193'

2016/03/06 13:45:42 client[33]: registered, is it master? false
2016/03/06 13:45:42 client[33]: starting main loop
2016/03/06 13:45:42 registry: requesting master 27 to send map
2016/03/06 13:45:42 client: registering client
2016/03/06 13:45:42 registry: registered new id 34 for player 'Guest679'
2016/03/06 13:45:42 registry: creating new unit for client 34, login 'Guest679'
2016/03/06 13:45:42 client[34]: registered, is it master? false
2016/03/06 13:45:42 client[34]: starting main loop
2016/03/06 13:45:43 registry: requesting master 27 to send map
2016/03/06 13:47:19 registry: removing client 33 with message: ErrmsgTooSlow
2016/03/06 13:47:19 client[33]: inbox closed, closing connection
2016/03/06 13:47:26 registry: removing client 27 with message: ErrmsgTooSlow
2016/03/06 13:47:26 registry: switching master 27 -> 34
2016/03/06 13:47:26 client[27]: inbox closed, closing connection
2016/03/06 13:56:22 client[34]: reciever failed to read message: EOF
2016/03/06 13:56:22 registry: removing client 34
2016/03/06 13:56:22 registry: switching master 34 -> 29
2016/03/06 13:56:23 client[29]: reciever failed to read message: EOF
2016/03/06 13:56:23 registry: removing client 29
2016/03/06 13:56:23 registry: no players left, cleaning up

**Comment by kremius** [comment]
handleNewData takes:  30.7364
readAll takes:  0.013586
New data length:  771
socketError()
QAbstractSocket::RemoteHostClosedError
void Game::endProcess()

Seems like the issue is in the client

**Comment by kremius** [comment]
TODO: check thread safety of toUnicode function (and overall QTextCodec)

**Comment by kremius** [comment]
Seems like done, but testing is needed

**Comment by kremius** [comment]
Marked as fixed, but can be reopened by results of the alpha test
