### ISSUE TITLE
Restart round button

### ISSUE THREAD

**Issue by kremius** [kremius/karya-valya#166]
It should be possible to set admin for the game, and it should be possible for admin to restart game

**Comment by mechmind** [comment]
Admin == master?

**Comment by kremius** [comment]
No.
Currently the server appoints a first client as a master client. This approach is simple, but as well it works only for simple cases. 
So it should be possible to make a list of logins for the server. Only clients with logins from that lists can  become masters.
I think, it is better to separate masters from admins.
I will add soon details to the protocol description.

**Comment by mechmind** [comment]
I think this issue realted to #119
