### ISSUE TITLE
Unsync detection on server

### ISSUE THREAD

**Issue by kremius** [kremius/karya-valya#88]
And server will send to unsync client YOU ARE UNSYNC SCUM

**Comment by kremius** [comment]
Really important

**Comment by kremius** [comment]
And also report generation on server

**Comment by mechmind** [comment]
From time to time all clients on same tick will send to server hashes of their maps to server. Server then collects all of those hashes and compare with master hash. If server finds mismatch it request master and ill client send their maps to server. Server then stores those dumps and logs this unsync event. The faulty client then dropped.

**Comment by kremius** [comment]
It is needed to think that should client do if the server says to upload a map from non saved tick (some ping spikes or slow client for example)

**Comment by kremius** [comment]
Tick value to tick message for verification

**Comment by kremius** [comment]
Cause of #201 it is needed to simplify implementation of the unsync detection

**Comment by kremius** [comment]
It is needed to break connection immediately after unsync (it is not needed to wait until the unsync client will upload map on the server)
